[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build-meta"

[project]
name = "dericdatapp"
version = "0.0.0"
description = "A quantitative data lens for preparation and profiling"
authors = [
    {name = "Deric"}
]
dependencies = [
    "pandas",
    "numpy"
]
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["dericdatapp*"]